[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
port = 8502
address = "localhost"
baseUrlPath = ""
enableStaticServing = false
runOnSave = false
allowRunOnSave = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "error"